### ISSUE TITLE
Shift one phase to bonus

### ISSUE THREAD

**Issue by quinnleong** [s-daoud/distillr#1]
Features on features! I would suggest moving either phase 6 or phase 8 to bonus. Things always take longer than expected during capstones, and this way you can still do every cool feature if there's time, but it's a little less pressure!

**Comment by s-daoud** [comment]
Okay, thanks! I moved phase 8 to the bonuses, and after thinking about it, I think there's some extra bonuses that I'd rather do before badges if there's time. So pulling that off the main timeline works great!
